name: flutter_plot
description: A pretty plotting package for Flutter apps.
version: 0.0.1
author: R. C. Howell
homepage:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
